[package]
name = "overlord"
version = "0.0.0"
authors = ["Eason Gao <kaoimin@qq.com>"]
edition = "2018"
license = "MIT"
include = ["Cargo.toml", "src/*", "README.md", "LICENSE", "rust-toolchain"]
readme = "README.md"
keywords = ["consensus", "bft", "distributed-systems"]
categories = ["algorithms"]
repository = "https://github.com/cryptape/overlord"
description = """
Overlord consensus procotol.
"""

[dependencies]
async-trait = "0.1"
bit-vec = "0.6"
bytes = "0.4"
derive_more = "0.15"
futures-preview = "0.3.0-alpha.17"
futures-timer = "0.3"
log = "0.4"
parking_lot = "0.9"
rand_core = "0.5"
rand_pcg = "0.2"
rlp = "0.4"
tokio = "0.2.0-alpha.1"

[dev-dependencies]
bincode = "1.1"
rand = "0.6"
serde = {version = "1.0", features = ["derive"]}
