[package]
name = "overlord"
version = "0.1.0"
authors = ["Eason Gao <kaoimin@qq.com>"]
edition = "2018"
license = "MIT"
include = ["Cargo.toml", "src/*", "README.md", "LICENSE", "rust-toolchain"]
readme = "README.md"
keywords = ["consensus", "bft", "distributed-systems"]
categories = ["algorithms"]
repository = "https://github.com/cryptape/overlord"
description = """
Overlord consensus procotol.
"""

[dependencies]
async-trait = "0.1"
bit-vec = "0.6"
bytes = { version = "0.4", features = ["serde"] }
creep = "0.1"
derive_more = "0.15"
futures = { version = "0.3", features = [ "async-await" ] }
futures-timer = "2.0"
hex = "0.4"
log = "0.4"
parking_lot = "0.9"
rand_core = "0.5"
rand_pcg = "0.2"
rlp = "0.4"
runtime = "0.3.0-alpha.7"
runtime-tokio = "0.3.0-alpha.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
bincode = "1.2"
blake2b_simd = "0.5"
crossbeam-channel = "0.3"
env_logger = "0.6"
hasher = { version = "0.1", features = ['hash-keccak'] }
lazy_static = "1.4"
rand = "0.6"